#!/usr/bin/env node
/**
 * Fill missing courseeventparams JSON files from the parsed geometry data
 * generated by alpha123/uma-skill-tools from the JP client assets.
 *
 * Global and JP use the same course geometry. Global's UnityFS content blocks
 * use a custom transform that stock UnityPy cannot decode, so this script syncs
 * the already-parsed geometry instead of pretending to dump the Global bundle.
 *
 * The source geometry is vendored under scripts/data-extract/vendor/ so normal
 * extraction runs are fully offline and the provenance lives in git history.
 * Use `--refresh` to re-download and re-pin the vendored snapshot.
 */

import { access, mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { isDeepStrictEqual } from 'node:util';
import { Command } from 'commander';
import { closeDatabase, openDatabase, queryAll } from '../master-data/database';
import { resolveMasterDbPath } from '../master-data/shared';

const SOURCE_REPO = 'alpha123/uma-skill-tools';
const SOURCE_PATH = 'data/course_data.json';
const DEFAULT_REF = 'master';
const VENDOR_DIR = path.resolve(import.meta.dirname, 'vendor');
const VENDOR_DATA_PATH = path.join(VENDOR_DIR, 'uma-skill-tools-course-data.json');
const VENDOR_META_PATH = path.join(VENDOR_DIR, 'uma-skill-tools-course-data.meta.json');
const DEFAULT_OUTPUT_DIR = 'courseeventparams';
const INTENTIONALLY_INCOMPLETE_COURSES = new Set(['11201', '11202']);

type Corner = {
  start: number;
  length: number;
};

type Straight = {
  start: number;
  end: number;
  frontType: number;
};

type Slope = {
  start: number;
  length: number;
  slope: number;
};

type SourceCourse = {
  distance: number;
  corners: Array<Corner>;
  straights: Array<Straight>;
  slopes: Array<Slope>;
};

type CourseEvent = {
  _paramType: number;
  _values: Array<number>;
  _distance: number;
};

type CourseEventParams = {
  m_GameObject: {
    m_FileID: number;
    m_PathID: number;
  };
  m_Enabled: number;
  m_Script: {
    m_FileID: number;
    m_PathID: number;
  };
  m_Name: string;
  courseParams: Array<CourseEvent>;
};

type CourseIdRow = {
  id: number;
};

type VendorMeta = {
  description: string;
  sourceRepo: string;
  sourcePath: string;
  ref: string;
  commit: string;
  url: string;
  fetchedAt: string;
};

type ExtractGeometryOptions = {
  dbPath?: string;
  outputDir: string;
  refresh: boolean;
  ref: string;
  force: boolean;
};

function getErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function fetchJson(url: string): Promise<unknown> {
  const response = await fetch(url, {
    headers: {
      Accept: 'application/json',
      'User-Agent': 'torena-sim-course-geometry-extractor'
    }
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText} for ${url}`);
  }

  return await response.json();
}

/**
 * Re-download the parsed geometry, pin it to the resolved commit SHA, and
 * rewrite the vendored snapshot plus its provenance metadata.
 */
async function refreshVendoredGeometry(ref: string): Promise<VendorMeta> {
  const commitInfo = (await fetchJson(
    `https://api.github.com/repos/${SOURCE_REPO}/commits/${ref}`
  )) as { sha?: string };
  const commit = commitInfo.sha;
  if (!commit) {
    throw new Error(`Could not resolve commit SHA for ${SOURCE_REPO}@${ref}`);
  }

  const url = `https://raw.githubusercontent.com/${SOURCE_REPO}/${commit}/${SOURCE_PATH}`;
  const geometry = (await fetchJson(url)) as Record<string, SourceCourse>;

  const meta: VendorMeta = {
    description:
      'Vendored parsed course geometry used to fill courseeventparams/*.json. Refresh with: pnpm run extract:geometry --refresh',
    sourceRepo: SOURCE_REPO,
    sourcePath: SOURCE_PATH,
    ref,
    commit,
    url,
    fetchedAt: new Date().toISOString()
  };

  await mkdir(VENDOR_DIR, { recursive: true });
  await writeFile(VENDOR_DATA_PATH, `${JSON.stringify(geometry, null, 1)}\n`, 'utf8');
  await writeFile(VENDOR_META_PATH, `${JSON.stringify(meta, null, 2)}\n`, 'utf8');
  console.log(`↻ Refreshed vendored geometry from ${SOURCE_REPO}@${commit}`);
  return meta;
}

async function loadVendoredGeometry(): Promise<Record<string, SourceCourse>> {
  let raw: string;
  try {
    raw = await readFile(VENDOR_DATA_PATH, 'utf8');
  } catch {
    throw new Error(
      `Vendored geometry not found at ${path.relative(process.cwd(), VENDOR_DATA_PATH)}. ` +
        'Run `pnpm run extract:geometry --refresh` to download it.'
    );
  }

  const meta = JSON.parse(await readFile(VENDOR_META_PATH, 'utf8')) as VendorMeta;
  console.log(
    `Using vendored geometry: ${meta.sourceRepo}@${meta.commit} (fetched ${meta.fetchedAt})`
  );
  return JSON.parse(raw) as Record<string, SourceCourse>;
}

// The client defines corner and slope geometry loosely: a segment may start at
// or past the finish marker and its length can overshoot the course distance
// (e.g. course 10613's final corner). The upstream extractor performs no bounds
// checks, so only reject values that are non-finite, negative-start, or
// zero/negative length.
function validateSegment(value: Corner | Slope, courseId: string): void {
  if (
    !Number.isFinite(value.start) ||
    !Number.isFinite(value.length) ||
    value.start < 0 ||
    value.length <= 0
  ) {
    throw new Error(`Course ${courseId} has an invalid segment: ${JSON.stringify(value)}`);
  }
}

function validateSourceCourse(courseId: string, course: SourceCourse): void {
  if (!Number.isFinite(course.distance) || course.distance <= 0) {
    throw new Error(`Course ${courseId} has an invalid distance`);
  }
  if (
    !Array.isArray(course.corners) ||
    !Array.isArray(course.straights) ||
    !Array.isArray(course.slopes)
  ) {
    throw new TypeError(`Course ${courseId} is missing a geometry array`);
  }
  // Corners and slopes are legitimately empty on straight-only sprints and flat
  // tracks, but every course runs along at least one straight.
  if (course.straights.length === 0) {
    throw new Error(`Course ${courseId} must contain at least one straight`);
  }

  for (const corner of course.corners) {
    validateSegment(corner, courseId);
  }
  for (const slope of course.slopes) {
    validateSegment(slope, courseId);
    if (!Number.isFinite(slope.slope)) {
      throw new TypeError(`Course ${courseId} has an invalid slope: ${JSON.stringify(slope)}`);
    }
  }
  for (const straight of course.straights) {
    if (
      !Number.isFinite(straight.start) ||
      !Number.isFinite(straight.end) ||
      !Number.isFinite(straight.frontType) ||
      straight.start < 0 ||
      straight.end <= straight.start
    ) {
      throw new Error(`Course ${courseId} has an invalid straight: ${JSON.stringify(straight)}`);
    }
  }
}

function buildCourseEventParams(course: SourceCourse): CourseEventParams {
  const courseParams: Array<CourseEvent> = [];

  for (const [index, corner] of course.corners.entries()) {
    courseParams.push({
      _paramType: 0,
      _values: [index + 1, corner.length],
      _distance: corner.start
    });
  }

  for (const straight of course.straights) {
    courseParams.push(
      {
        _paramType: 2,
        _values: [1, straight.frontType],
        _distance: straight.start
      },
      {
        _paramType: 2,
        _values: [2, straight.frontType],
        _distance: straight.end
      }
    );
  }

  for (const slope of course.slopes) {
    courseParams.push({
      _paramType: 11,
      _values: [slope.slope, slope.length],
      _distance: slope.start
    });
  }

  return {
    // These Unity object references are irrelevant to course extraction. Keep
    // the keys so generated files retain the shape of client typetree dumps.
    m_GameObject: { m_FileID: 0, m_PathID: 0 },
    m_Enabled: 1,
    m_Script: { m_FileID: 0, m_PathID: 0 },
    m_Name: '',
    courseParams
  };
}

function parseGeneratedGeometry(
  params: CourseEventParams
): Pick<SourceCourse, 'corners' | 'straights' | 'slopes'> {
  const corners: Array<Corner> = [];
  const straights: Array<Straight> = [];
  const slopes: Array<Slope> = [];
  let pendingStraight: Pick<Straight, 'start' | 'frontType'> | null = null;

  for (const event of params.courseParams) {
    if (event._paramType === 0) {
      corners.push({ start: event._distance, length: event._values[1] });
    } else if (event._paramType === 2 && event._values[0] === 1) {
      if (pendingStraight) {
        throw new Error('Generated geometry starts a straight before ending the previous one');
      }
      pendingStraight = { start: event._distance, frontType: event._values[1] };
    } else if (event._paramType === 2 && event._values[0] === 2) {
      if (!pendingStraight) {
        throw new Error('Generated geometry ends a straight before starting it');
      }
      straights.push({ ...pendingStraight, end: event._distance });
      pendingStraight = null;
    } else if (event._paramType === 11) {
      slopes.push({ start: event._distance, slope: event._values[0], length: event._values[1] });
    }
  }

  if (pendingStraight) {
    throw new Error('Generated geometry leaves a straight open');
  }

  return { corners, straights, slopes };
}

function validateRoundTrip(
  courseId: string,
  source: SourceCourse,
  generated: CourseEventParams
): void {
  const parsed = parseGeneratedGeometry(generated);
  for (const key of ['corners', 'straights', 'slopes'] as const) {
    if (!isDeepStrictEqual(parsed[key], source[key])) {
      throw new Error(`Course ${courseId} failed ${key} round-trip validation`);
    }
  }
}

async function extractGeometry(options: ExtractGeometryOptions): Promise<Array<string>> {
  if (options.refresh) {
    await refreshVendoredGeometry(options.ref);
  }

  const dbPath = await resolveMasterDbPath(options.dbPath);
  const outputDir = path.resolve(process.cwd(), options.outputDir);
  const db = openDatabase(dbPath);

  let courseIds: Array<string>;
  try {
    courseIds = queryAll<CourseIdRow>(db, 'SELECT id FROM race_course_set ORDER BY id').map((row) =>
      row.id.toString()
    );
  } finally {
    closeDatabase(db);
  }

  const targets: Array<string> = [];
  for (const courseId of courseIds) {
    if (INTENTIONALLY_INCOMPLETE_COURSES.has(courseId)) {
      continue;
    }
    const outputPath = path.join(outputDir, `${courseId}.json`);
    if (options.force || !(await fileExists(outputPath))) {
      targets.push(courseId);
    }
  }

  if (targets.length === 0) {
    console.log('✓ Course geometry is already complete for every current master.mdb course');
    return [];
  }

  const sourceGeometry = await loadVendoredGeometry();
  await mkdir(outputDir, { recursive: true });

  const missingFromSource = targets.filter((courseId) => !sourceGeometry[courseId]);
  if (missingFromSource.length > 0) {
    throw new Error(
      `Geometry source is missing current course IDs: ${missingFromSource.join(', ')}`
    );
  }

  const written: Array<string> = [];
  for (const courseId of targets) {
    const sourceCourse = sourceGeometry[courseId];
    validateSourceCourse(courseId, sourceCourse);
    const generated = buildCourseEventParams(sourceCourse);
    validateRoundTrip(courseId, sourceCourse, generated);

    const outputPath = path.join(outputDir, `${courseId}.json`);
    await writeFile(outputPath, `${JSON.stringify(generated, null, 2)}\n`, 'utf8');
    console.log(
      `✓ ${path.relative(process.cwd(), outputPath)} (${sourceCourse.corners.length} corners, ${sourceCourse.straights.length} straights, ${sourceCourse.slopes.length} slopes)`
    );
    written.push(courseId);
  }

  console.log(`\n✓ Wrote ${written.length} course geometry file${written.length === 1 ? '' : 's'}`);
  return written;
}

async function main(): Promise<void> {
  const program = new Command();
  program
    .name('extract-geometry')
    .description('Fill missing courseeventparams files from maintained parsed client geometry')
    .argument('[dbPath]', 'path to master.mdb')
    .argument(
      '[outputDir]',
      `output directory (default: ${DEFAULT_OUTPUT_DIR})`,
      DEFAULT_OUTPUT_DIR
    )
    .option('--refresh', 're-download and re-pin the vendored source snapshot', false)
    .option('--ref <ref>', `git ref to pin when refreshing (default: ${DEFAULT_REF})`, DEFAULT_REF)
    .option('--force', 'rewrite geometry for every non-placeholder course', false);

  program.parse(process.argv);
  const cliOptions = program.opts<{ refresh: boolean; ref: string; force: boolean }>();
  const [dbPath, outputDir = DEFAULT_OUTPUT_DIR] = program.args as Array<string>;

  await extractGeometry({
    dbPath,
    outputDir,
    refresh: cliOptions.refresh,
    ref: cliOptions.ref,
    force: cliOptions.force
  });
}

if (import.meta.main) {
  main().catch((error) => {
    console.error(`Error: ${getErrorMessage(error)}`);
    process.exit(1);
  });
}

export { buildCourseEventParams, extractGeometry, parseGeneratedGeometry, validateRoundTrip };
